services:
  - name: exam-checker
    type: web
    port: 8000
    env:
      - name: STD_SEAT_NUM
        secret: true
      - name: to_email_addr
        secret: true
      - name: from_email_addr
        secret: true
      - name: from_email_pass
        secret: true
    build:
      command: pip install -r requirements.txt
    run: python exam_checker.py
    deployment:
      restart_policy: never
